### PR TITLE
Add more cheats

### PR DESCRIPTION
**Pull request by jpenguin**
May be a bit much, I don't know- something to think about.

### CODE REVIEW

**Comment by jpenguin** [comment]
#3

**Comment by foote-darrell** [comment]
Thanks. Does this need to be compiled, or is there an executable build of this version already?

**Comment by foote-darrell** [comment]
Another modification I want is to make the Jump-Jet fly indefinitely until you stop it. Is that a practical thing to do?

**Comment by foote-darrell** [comment]
How can you make it so the growth potion effect lasts longer? It is much to short as it is by default.

**Comment by jpenguin** [comment]
Yes, my mod would have to be compiled, it can take a while on a pi...

I don't know where the jump-jet & growth timers are, but I'm sure they can be changed if you look

**Pull request closed without merging**
